name        : awesome
version     : 4.2
release     : 1
source      :
    - https://github.com/awesomeWM/awesome/releases/download/v4.2/awesome-4.2.tar.bz2 : 9a40a5a90152bc911b6bab922f5541ed8b230fd8847df9c995f289600752b5ca
license     :
    - GPL-2.0
summary     : Awesome Window Manager
description : |
  Awesome is a highly configurable, next generation framework window manager for X.
builddeps:
  - pkgconfig(cairo)
  - pkgconfig(pango)
  - pkgconfig(libstartup-notification-1.0)
  - pkgconfig(xcb-cursor)
  - pkgconfig(xcb-icccm)
  - pkgconfig(xcb-keysyms)
  - pkgconfig(xcb-xrm)
  - pkgconfig(xcb-util)
  - pkgconfig(xkbcommon-x11)
  - libxdg-basedir-devel
  - gdk-pixbuf-devel
  - lua-devel
  - lua-lgi
  - imagemagick-devel
  - asciidoc
  - gzip
  - dbus-devel
rundeps:
  lua
  lua-lgi
build       : |
    %make
install     : |
    %make_install
